#!/usr/bin/env python3
"""Restore and validate the release keystore before a long Android build.

The script deliberately reads secrets from the environment instead of accepting
passwords as command-line arguments. It removes UTF-8 BOM/CRLF contamination,
validates the restored store and key entry with keytool, and writes the exact
keystore.properties consumed by app/build.gradle.kts.
"""

from __future__ import annotations

import argparse
import base64
import binascii
import hashlib
import os
import shutil
import subprocess
import sys
from pathlib import Path

SECRET_NAMES = (
    "KEYSTORE_BASE64",
    "KEYSTORE_PASSWORD",
    "KEY_ALIAS",
    "KEY_PASSWORD",
)


def normalize_text(value: str, field: str) -> str:
    """Remove transport contamination without changing internal password text."""
    cleaned = value.replace("\ufeff", "").replace("ï»¿", "").strip()
    if not cleaned:
        raise ValueError(f"{field} is empty after BOM/whitespace cleanup")
    return cleaned


def decode_keystore(value: str) -> bytes:
    cleaned = value.replace("\ufeff", "").replace("ï»¿", "")
    cleaned = "".join(cleaned.split())
    try:
        return base64.b64decode(cleaned, validate=True)
    except (binascii.Error, ValueError) as error:
        raise ValueError("KEYSTORE_BASE64 is not valid base64") from error


def require_secrets() -> dict[str, str]:
    missing = [name for name in SECRET_NAMES if not os.environ.get(name)]
    if missing:
        raise ValueError("missing GitHub Actions secrets: " + ", ".join(missing))
    return {
        "store_password": normalize_text(os.environ["KEYSTORE_PASSWORD"], "KEYSTORE_PASSWORD"),
        "alias": normalize_text(os.environ["KEY_ALIAS"], "KEY_ALIAS"),
        "key_password": normalize_text(os.environ["KEY_PASSWORD"], "KEY_PASSWORD"),
        "keystore_base64": os.environ["KEYSTORE_BASE64"],
    }


def keytool_path() -> str:
    java_home = os.environ.get("JAVA_HOME")
    candidates = []
    if java_home:
        candidates.append(Path(java_home) / "bin" / "keytool")
        candidates.append(Path(java_home) / "bin" / "keytool.exe")
    found = shutil.which("keytool")
    if found:
        candidates.append(Path(found))
    for candidate in candidates:
        if candidate.is_file():
            return str(candidate)
    raise RuntimeError("keytool was not found; configure JDK before signing preflight")


def run_keytool(args: list[str], env: dict[str, str], stage: str) -> str:
    command = [
        keytool_path(),
        "-J-Duser.language=en",
        "-J-Duser.country=US",
        *args,
    ]
    result = subprocess.run(command, env=env, capture_output=True, text=True)
    if result.returncode != 0:
        detail = (result.stderr or result.stdout).strip().splitlines()
        safe_detail = detail[-1] if detail else "no keytool diagnostic"
        raise RuntimeError(f"keystore preflight {stage} failed: {safe_detail}")
    return result.stdout


def write_properties(path: Path, keystore_path: Path, values: dict[str, str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    content = "\n".join(
        (
            "# Generated by ci/script/validate_release_signing.py",
            f"storeFile={keystore_path.resolve()}",
            f"storePassword={values['store_password']}",
            f"keyAlias={values['alias']}",
            f"keyPassword={values['key_password']}",
            "",
        ),
    )
    path.write_text(content, encoding="utf-8", newline="\n")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--keystore-out", type=Path, required=True)
    parser.add_argument("--properties-out", type=Path, required=True)
    args = parser.parse_args()
    try:
        values = require_secrets()
        keystore_bytes = decode_keystore(values["keystore_base64"])
        if len(keystore_bytes) < 32:
            raise ValueError("decoded keystore is unexpectedly small")
        args.keystore_out.parent.mkdir(parents=True, exist_ok=True)
        args.keystore_out.write_bytes(keystore_bytes)
        os.chmod(args.keystore_out, 0o600)
        digest = hashlib.sha256(keystore_bytes).hexdigest()

        tool_env = os.environ.copy()
        tool_env["MUSE_STORE_PASSWORD"] = values["store_password"]
        tool_env["MUSE_KEY_PASSWORD"] = values["key_password"]
        run_keytool(
            [
                "-list",
                "-keystore",
                str(args.keystore_out),
                "-storepass:env",
                "MUSE_STORE_PASSWORD",
            ],
            tool_env,
            "store password",
        )
        fingerprint = run_keytool(
            [
                "-list",
                "-v",
                "-keystore",
                str(args.keystore_out),
                "-storepass:env",
                "MUSE_STORE_PASSWORD",
                "-alias",
                values["alias"],
                "-keypass:env",
                "MUSE_KEY_PASSWORD",
            ],
            tool_env,
            "alias/key password",
        )
        write_properties(args.properties_out, args.keystore_out, values)
        fingerprint_line = next(
            (line.strip() for line in fingerprint.splitlines() if "SHA-256" in line),
            "fingerprint unavailable",
        )
        print(f"release signing preflight PASS: bytes={len(keystore_bytes)} sha256={digest}")
        print(f"alias={values['alias']} {fingerprint_line}")
        print(f"properties={args.properties_out.resolve()}")
        return 0
    except (OSError, RuntimeError, ValueError) as error:
        print(f"release signing preflight failed: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
